# Generated by Django 5.2 on 2026-10-02 21:57

import django.db.models.deletion
import wallets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lealtad', '0008_remove_tarjetalealtad_color_fondo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=wallets.models.pass_token, editable=False, max_length=64)),
                ('google_requested', models.BooleanField(default=False)),
                ('tarjeta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_identity', to='lealtad.tarjetalealtad')),
            ],
        ),
        migrations.CreateModel(
            name='WalletUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='wallets.walletidentity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('push_token', models.CharField(max_length=256)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='wallets.walletidentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identity', 'device_id'), name='apple_device_pass_unique')],
            },
        ),
    ]
