# Generated by Django 5.2 on 2026-10-02 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('stores', '0002_alter_store_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='stores.store'),
        ),
    ]
