# Generated by Django 5.2 on 2026-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN hasheado para el login del cliente (card_code + PIN). Nunca se guarda en texto plano.', max_length=128),
        ),
    ]
