# Generated by Django 5.2 on 2026-10-02 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_costumer_pin'),
        ('stores', '0002_alter_store_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='costumer',
            constraint=models.UniqueConstraint(fields=('store', 'telefono'), name='cliente_telefono_por_negocio'),
        ),
        migrations.AddConstraint(
            model_name='costumer',
            constraint=models.UniqueConstraint(fields=('store', 'email'), name='cliente_email_por_negocio'),
        ),
    ]
