# Generated by Django 5.2 on 2026-10-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0004_require_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN hasheado para el login del cliente (negocio + teléfono + PIN). Nunca se guarda en texto plano.', max_length=128),
        ),
    ]
