# Generated by Django 5.2 on 2026-09-07 03:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocio/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='negocio/favicon/')),
                ('color_primario', models.CharField(blank=True, default='#405189', help_text='Color hexadecimal, ej. #405189', max_length=7)),
                ('color_secundario', models.CharField(blank=True, default='#f3f6f9', help_text='Color hexadecimal, ej. #f3f6f9', max_length=7)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
