# Generated by Django 5.2 on 2026-09-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['creado_en']},
        ),
    ]
