# Generated by Django 5.2 on 2026-10-02 21:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_alter_store_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('moneda', models.CharField(choices=[('MXN', 'MXN')], default='MXN', max_length=3)),
                ('intervalo_meses', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PREPARACION', 'En preparación'), ('PRUEBA', 'Periodo de prueba'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PREPARACION', max_length=15)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('proveedor_id', models.CharField(blank=True, max_length=150)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='suscripcion', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudSuscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(max_length=3)),
                ('intervalo_meses', models.PositiveSmallIntegerField()),
                ('email_pagador', models.EmailField(max_length=254)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='PREPARADA', editable=False, max_length=30)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='billing.suscripcion')),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_id', models.CharField(max_length=150, unique=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('estado', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='billing.suscripcion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
