# Generated by Django 5.2 on 2026-09-07 03:25

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('monto_base', models.DecimalField(decimal_places=2, help_text="Monto gastado que otorga 'puntos_otorgados' puntos, ej. 10.00", max_digits=10)),
                ('puntos_otorgados', models.PositiveIntegerField(help_text="Puntos otorgados por cada 'monto_base' gastado.")),
                ('meta_puntos', models.PositiveIntegerField(help_text='Puntos necesarios para alcanzar el premio.')),
                ('descripcion_premio', models.CharField(max_length=255)),
                ('vigente_desde', models.DateTimeField()),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('actualizado_por', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_puntos', to='stores.store')),
            ],
            options={
                'verbose_name': 'Regla de puntos',
                'verbose_name_plural': 'Reglas de puntos',
                'ordering': ['-vigente_desde'],
            },
        ),
    ]
