# Generated by Django 5.2 on 2026-09-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
        ('lealtad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaLealtad',
            fields=[
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tarjeta', serialize=False, to='costumers.costumer')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de lealtad',
                'verbose_name_plural': 'Tarjetas de lealtad',
            },
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACUMULACION', 'Acumulación'), ('CANJE', 'Canje'), ('AJUSTE', 'Ajuste')], max_length=15)),
                ('puntos', models.IntegerField(help_text='Positivo en acumulación/ajuste positivo, negativo en canje.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='lealtad.tarjetalealtad')),
            ],
            options={
                'verbose_name': 'Movimiento de puntos',
                'verbose_name_plural': 'Movimientos de puntos',
                'ordering': ['-fecha'],
            },
        ),
    ]
