# Generated by Django 5.2 on 2026-09-07 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('lealtad', '0002_tarjetalealtad_movimientopuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientopuntos',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='compras.compra'),
        ),
    ]
