# Generated by Django 5.2 on 2026-09-08 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lealtad', '0003_movimientopuntos_compra'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_consumidos', models.PositiveIntegerField()),
                ('premio', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes_registrados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='locations.sucursal')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='lealtad.tarjetalealtad')),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='movimientopuntos',
            name='canje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='lealtad.canje'),
        ),
    ]
