# Generated by Django 5.2 on 2026-09-24 18:45

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lealtad', '0004_canje_movimientopuntos_canje'),
        ('locations', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_mecanica', models.CharField(choices=[('MONTO', 'Por monto de compra'), ('VISITA', 'Por visita (sello/casilla)')], default='MONTO', max_length=10)),
                ('monto_base', models.DecimalField(blank=True, decimal_places=2, help_text="Solo para tipo MONTO: monto gastado que otorga 'puntos_otorgados' puntos, ej. 10.00", max_digits=10, null=True)),
                ('puntos_otorgados', models.PositiveIntegerField(help_text="Puntos por cada 'monto_base' gastado (MONTO), o puntos fijos por escaneo (VISITA).")),
                ('meta_puntos', models.PositiveIntegerField(help_text='Puntos (o casillas, si es VISITA) necesarios para alcanzar el premio.')),
                ('descripcion_premio', models.CharField(max_length=255)),
                ('vigente_desde', models.DateTimeField()),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('actualizado_por', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='stores.store')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='RestriccionPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_escaneos_dia', models.PositiveSmallIntegerField(default=1)),
                ('alcance', models.CharField(choices=[('SUCURSAL', 'Por sucursal'), ('NEGOCIO', 'Por negocio (todas las sucursales)')], default='SUCURSAL', max_length=10)),
                ('promocion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restriccion', to='lealtad.promocion')),
            ],
            options={
                'verbose_name': 'Restricción de promoción',
                'verbose_name_plural': 'Restricciones de promoción',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_otorgados', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='locations.sucursal')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='lealtad.tarjetalealtad')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='movimientopuntos',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='lealtad.visita'),
        ),
        migrations.DeleteModel(
            name='ReglaPuntos',
        ),
    ]
