# Generated by Django 5.2 on 2026-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lealtad', '0005_promocion_restriccionpromocion_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetalealtad',
            name='color_fondo',
            field=models.CharField(blank=True, help_text="Color hex para la opción 'Color personalizado', ej. #405189.", max_length=7),
        ),
        migrations.AddField(
            model_name='tarjetalealtad',
            name='estilo_fondo',
            field=models.CharField(blank=True, choices=[('', 'Color de marca del negocio'), ('atardecer', 'Atardecer'), ('oceano', 'Océano'), ('bosque', 'Bosque'), ('noche', 'Noche'), ('dorado', 'Dorado'), ('personalizado', 'Color personalizado')], help_text="Fondo prediseñado de la tarjeta. 'Color personalizado' usa color_fondo.", max_length=20),
        ),
    ]
