# Generated by Django 5.2 on 2026-09-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lealtad', '0006_tarjetalealtad_color_fondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetalealtad',
            name='sello_imagen',
            field=models.ImageField(blank=True, help_text='Ícono propio para cada sello/visita de la tarjeta (opcional). Sin uno, se usa una estrella por default.', null=True, upload_to='tarjetas/sellos/'),
        ),
    ]
