# Generated by Django 5.2 on 2026-09-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lealtad', '0007_tarjetalealtad_sello_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetalealtad',
            name='color_fondo',
        ),
        migrations.RemoveField(
            model_name='tarjetalealtad',
            name='estilo_fondo',
        ),
        migrations.RemoveField(
            model_name='tarjetalealtad',
            name='sello_imagen',
        ),
        migrations.AddField(
            model_name='promocion',
            name='color_fondo',
            field=models.CharField(blank=True, help_text="Color hex para la opción 'Color personalizado', ej. #405189.", max_length=7),
        ),
        migrations.AddField(
            model_name='promocion',
            name='estilo_fondo',
            field=models.CharField(blank=True, choices=[('', 'Color de marca del negocio'), ('atardecer', 'Atardecer'), ('oceano', 'Océano'), ('bosque', 'Bosque'), ('noche', 'Noche'), ('dorado', 'Dorado'), ('personalizado', 'Color personalizado')], help_text="Fondo prediseñado de la tarjeta. 'Color personalizado' usa color_fondo.", max_length=20),
        ),
        migrations.AddField(
            model_name='promocion',
            name='sello_imagen',
            field=models.ImageField(blank=True, help_text='Ícono para cada sello/visita de la tarjeta (opcional, solo mecánica VISITA). Sin uno, se usa una estrella por default.', null=True, upload_to='promociones/sellos/'),
        ),
    ]
