"""
Django settings for rewards project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get('DJANGO_DEBUG', '0') == '1'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'development-only-not-for-production'
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured('Configura DJANGO_SECRET_KEY o DJANGO_DEBUG=1 para desarrollo.')

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'costumers',
    'stores',
    'locations',
    'bases',
    'cuentas',
    'lealtad',
    'compras',
    'core',
    'billing',
    'wallets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'billing.middleware.SubscriptionMiddleware',
    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rewards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stores.context_processors.negocio',
            ],
        },
    },
]

WSGI_APPLICATION = 'rewards.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'America/Mexico_City')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'login'

# --- Wallets (Apple / Google) ---
# Si faltan credenciales, el WalletProvider correspondiente se reporta
# como no configurado: los botones se ocultan y los endpoints devuelven
# un aviso en vez de romper la app. Ver NUEVAS_DEPENDENCIAS.md / README.

# Apple Wallet: requiere cuenta de desarrollador Apple con Pass Type ID.
APPLE_WALLET_TEAM_ID = os.environ.get('APPLE_WALLET_TEAM_ID', '')
APPLE_WALLET_PASS_TYPE_ID = os.environ.get('APPLE_WALLET_PASS_TYPE_ID', '')
APPLE_WALLET_CERTIFICATE_PATH = os.environ.get('APPLE_WALLET_CERTIFICATE_PATH', '')
APPLE_WALLET_KEY_PATH = os.environ.get('APPLE_WALLET_KEY_PATH', '')
APPLE_WALLET_KEY_PASSWORD = os.environ.get('APPLE_WALLET_KEY_PASSWORD', '')
APPLE_WALLET_WWDR_PATH = os.environ.get('APPLE_WALLET_WWDR_PATH', '')

# Google Wallet: requiere cuenta de servicio de Google Cloud con acceso
# a la Google Wallet API, y un Issuer ID (developers.google.com/wallet).
GOOGLE_WALLET_ISSUER_ID = os.environ.get('GOOGLE_WALLET_ISSUER_ID', '')
GOOGLE_WALLET_SERVICE_ACCOUNT_FILE = os.environ.get('GOOGLE_WALLET_SERVICE_ACCOUNT_FILE', '')
GOOGLE_WALLET_CLASS_SUFFIX = os.environ.get('GOOGLE_WALLET_CLASS_SUFFIX', 'rewards_loyalty_class')

STATIC_ROOT = BASE_DIR / "staticfiles"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_REFERRER_POLICY = "same-origin"
CSRF_TRUSTED_ORIGINS = [x.strip() for x in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if x.strip()]
# Offline preparation only. No payment network transport is enabled.
MERCADOPAGO_ACCESS_TOKEN = os.environ.get("MERCADOPAGO_ACCESS_TOKEN", "")
MERCADOPAGO_WEBHOOK_SECRET = os.environ.get("MERCADOPAGO_WEBHOOK_SECRET", "")
BILLING_ENFORCE_SUBSCRIPTION = os.environ.get("BILLING_ENFORCE_SUBSCRIPTION", "0") == "1"

WALLET_SYNC_ENABLED = os.environ.get("WALLET_SYNC_ENABLED", "0") == "1"
WALLET_SERVICE_URL = os.environ.get("WALLET_SERVICE_URL", "")
if WALLET_SERVICE_URL and not WALLET_SERVICE_URL.startswith("https://"):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("WALLET_SERVICE_URL debe usar HTTPS.")
